---

composer_dir: /usr/share/composer
phpcs_bin: /usr/bin/phpcs

composer_global_require:
  - { package: 'drupal/coder', version: ':dev-8.x-2.x' }
  - { package: 'squizlabs/php_codesniffer', version: '=2.*' }

git_repos:
  - { branch: 'master', repo: 'http://git.drupal.org/sandbox/coltrane/1921926.git', name: 'DrupalSecure' } # git clone --branch master http://git.drupal.org/sandbox/coltrane/1921926.git DrupalSecure
  - { branch: '8.x-1.x', repo: 'https://github.com/klausi/drupalpractice.git', name: 'DrupalPractice' } #git clone --branch 8.x-1.x https://github.com/klausi/drupalpractice.git DrupalPractice
  - { branch: 'master', repo: 'https://github.com/podarok/Symfony2-coding-standard.git', name: 'Symfony2' }

phpcs_standards:
  - { path: 'vendor/drupal/coder/coder_sniffer/Drupal', name: 'Drupal' } #/root/.composer/vendor/drupal/coder/coder_sniffer/Drupal Drupal
  - { path: 'vendor/podarok/DrupalSecure/DrupalSecure', name: 'DrupalSecure' } #/root/.composer/vendor/podarok/DrupalSecure DrupalSecure
  - { path: 'vendor/podarok/DrupalPractice/DrupalPractice', name: 'DrupalPractice' } #/root/.composer/vendor/podarok/DrupalPractice DrupalPractice
  - { path: 'vendor/podarok/Symfony2', name: 'Symfony2' }

npm_packages:
  - jshint

gem_packages:
  - scss-lint

sniffers_apt_repos:
  - ppa:chris-lea/node.js

sniffers_apt_packages:
  - ruby1.9.1
  - ruby1.9.1-dev
  - rubygems1.9.1
  - irb1.9.1
  - ri1.9.1
  - rdoc1.9.1
  - build-essential
  - libopenssl-ruby1.9.1
  - libssl-dev
  - zlib1g-dev
  - nodejs
